### ISSUE TITLE
No linux-64(32) packages uploaded for 6.0.0

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/ipyparallel-feedstock#19]
See https://anaconda.org/conda-forge/ipyparallel/files

**Comment by jakirkham** [comment]
They appear to be there. 😕 Also conda-forge does not support 32-bit at this time. So only 64-bit.

<img width="1552" alt="screen shot 2017-02-10 at 19 37 41" src="https://cloud.githubusercontent.com/assets/3019665/22849155/70212864-efc8-11e6-8955-c1db45e7eb80.png">
