### ISSUE TITLE
no py36 version

### ISSUE THREAD

**Issue by jschueller** [conda-forge/ipyparallel-feedstock#21]
rerendering the feedstock does not update the linux docker script, only travis.yml and appveyor.yml

**Comment by minrk** [comment]
There seems to be some dependency preventing a linux py36 build. I'm not entirely sure how to identify it, though.

**Comment by jakirkham** [comment]
Why are we skipping Python 3.6 in `nbconvert`? Could this be related?

ref: https://github.com/conda-forge/nbconvert-feedstock/blob/5690f2b55bd55d6a4925f11f11b9d6b8993f6b3d/recipe/meta.yaml#L16

Edit: Commit history points to `pandocfilters`, which now exists on Python 3.6.

**Comment by jakirkham** [comment]
Adding Python 3.6 for `nbconvert` in PR ( https://github.com/conda-forge/nbconvert-feedstock/pull/12 ).

**Comment by minrk** [comment]
Thanks for tracking that down, @jakirkham! Rerendering here after the nbconvert finishes uploading should do it then?

**Comment by jakirkham** [comment]
Apparently not. Overlooked the selectors in our current recipe. Seems they cause the issue even though they shouldn't. This relates to a known `conda-smithy` issue. Though it is interesting that it only affected the Linux build and not the other OSes. PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/23 ) should get things back to working order.
