### ISSUE TITLE
ipcluster not working on 6.0.2

### ISSUE THREAD

**Issue by abjer** [conda-forge/ipyparallel-feedstock#26]
I have a problem with using `ipyparallel`. I have installed 6.0.2 on various Windows machines (server and non-server editions) from conda-forge. When I start `ipcluster` from the cmd prompt I get the following error.

`Fatal error in launcher: Unable to create process using '"'`

The error does not occur when installing `ipyparallel` through the standard conda channel.

**Comment by abjer** [comment]
@minrk - have you seen this issue?

**Comment by minrk** [comment]
I haven't seen this, it is strange. Is the version the same when it works, or is it an older version?

**Comment by abjer** [comment]
Appears to be same version. I am away from a pc until the 14th - will confirm then.

**Comment by abjer** [comment]
@minrk Yes, just checked up on it - they are both 6.0.2

**Comment by abjer** [comment]
@minrk just checked the feedstock and it still has the same issue. The latest commits did not fix the issue.

**Comment by bluescarni** [comment]
Seeing the same behaviour here on a fresh conda install on Windows.

BTW, any specific reason why 6.1.1 is not available on Python 3.6 on Windows? On python 3.5, ipyparallel 6.1.1 is working fine and does not exhibit this issue.

**Comment by thomasaarholt** [comment]
**Solved**:
Python 3.6, Windows: Solved by specifying version 6.1.1: `conda install ipyparallel=6.1.1`
Oddly, conda was installing 6.0.2 when I just called `conda install ipyparallel`

**Comment by jakirkham** [comment]
The Windows builds were missing because of a faulty re-rendering. A new re-rendering is being done in PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/32 ), which should fix this issue.

**Comment by jakirkham** [comment]
There really aren't any significant differences between the `defaults` and `conda-forge` builds. So presumably just a newer version of `ipyparallel` should fix this issue.

ref: https://github.com/conda-forge/ipyparallel-feedstock/compare/conda-forge:9f69bc15cab0346fca2ee3903c6c97c9643649d6...AnacondaRecipes:13b778def94ef9455d803080861a09988e02149f
