### ISSUE TITLE
Enabling `IPython Clusters` in notebook

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ipyparallel-feedstock#5]
Would like to propose that we enable this automatically for the user using post-link and post-unlink scripts. However, unlike other such scripts, we cannot guarantee the notebook is installed (as this can be used independently). So, if we do this, we need to check that the notebook exists and/or fail gracefully possibly with a warning.

**Comment by minrk** [comment]
I've been meaning to do this. 👍

**Comment by jakirkham** [comment]
Trying to do this in PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/6 ).
