### ISSUE TITLE
Drop `jlpm` build steps next release

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ipyparallel-feedstock#65]
Opening this as a reminder to drop the `jlpm` build steps from the recipe ( https://github.com/conda-forge/ipyparallel-feedstock/pull/64 ) as these were fixed upstream ( https://github.com/ipython/ipyparallel/pull/642 )

https://github.com/conda-forge/ipyparallel-feedstock/blob/5f2ffabca8b9f90e18226414f145423cee56bcae/recipe/meta.yaml#L24-L26

cc @bollwyvl (in case I missed anything else we should do then)

**Comment by bollwyvl** [comment]
Right. Everything related to `nodejs`, `jlpm`, etc. can be removed. The `third-party-licenses.json` [appears to be getting built](https://github.com/ipython/ipyparallel/runs/4391762922?check_suite_focus=true#step:5:888), and all of the tests stuff can all stay, and should help catch future packaging issues... could probably get these into upstream CI as well.

**Comment by bollwyvl** [comment]
Closed by #66
